const actionTypes = {
  AUTH_USER_BEGIN: "AUTH_USER_BEGIN",
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
  AUTH_USER_ERROR: "AUTH_USER_ERROR",
  LOGOUT_USER: "LOGOUT_USER",

  UPDATE_USER_BEGIN: "UPDATE_USER_BEGIN",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
};

export default actionTypes;
