const actionTypes = {
  CREATE_JOB_BEGIN: "CREATE_JOB_BEGIN",
  CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS",
  CREATE_JOB_ERROR: "CREATE_JOB_ERROR",

  GET_JOBS_BEGIN: "GET_JOBS_BEGIN",
  GET_JOBS_SUCCESS: "GET_JOBS_SUCCESS",

  SET_EDIT_JOB: "SET_EDIT_JOB",
  EDIT_JOB_BEGIN: "EDIT_JOB_BEGIN",
  EDIT_JOB_SUCCESS: "EDIT_JOB_SUCCESS",
  EDIT_JOB_ERROR: "EDIT_JOB_ERROR",

  DELETE_JOB_BEGIN: "DELETE_JOB_BEGIN",
  DELETE_JOB_END: "DELETE_JOB_END",
};

export default actionTypes;
