const actionTypes = {
  SHOW_CONFIRM_DIALOG: "SHOW_CONFIRM_DIALOG",
  HIDE_CONFIRM_DIALOG: "HIDE_CONFIRM_DIALOG",

  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  DISPLAY_ALERT: "SHOW_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",

  HANDLE_CHANGE: "HANDLE_CHANGE",
  CLEAR_VALUES: "CLEAR_VALUES",

  CLEAR_FILTERS: "CLEAR_FILTERS",
  CHANGE_PAGE: "CHANGE_PAGE",
};

export default actionTypes;
