const actionTypes = {
  DISPLAY_ALERT: "SHOW_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",

  AUTH_USER_BEGIN: "AUTH_USER_BEGIN",
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
  AUTH_USER_ERROR: "AUTH_USER_ERROR",

  UPDATE_USER_BEGIN: "UPDATE_USER_BEGIN",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",

  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  LOGOUT_USER: "LOGOUT_USER",

  HANDLE_CHANGE: "HANDLE_CHANGE",
  CLEAR_VALUES: "CLEAR_VALUES",

  CREATE_JOB_BEGIN: "CREATE_JOB_BEGIN",
  CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS",
  CREATE_JOB_ERROR: "CREATE_JOB_ERROR",

  GET_JOBS_BEGIN: "GET_JOBS_BEGIN",
  GET_JOBS_SUCCESS: "GET_JOBS_SUCCESS",

  SET_EDIT_JOB: "SET_EDIT_JOB",

  EDIT_JOB_BEGIN: "EDIT_JOB_BEGIN",
  EDIT_JOB_SUCCESS: "EDIT_JOB_SUCCESS",
  EDIT_JOB_ERROR: "EDIT_JOB_ERROR",

  DELETE_JOB_BEGIN: "DELETE_JOB_BEGIN",
  DELETE_JOB_END: "DELETE_JOB_END",

  SHOW_CONFIRM_DIALOG: "SHOW_CONFIRM_DIALOG",
  HIDE_CONFIRM_DIALOG: "HIDE_CONFIRM_DIALOG",

  SHOW_STATS_BEGIN: "SHOW_STATS_BEGIN",
  SHOW_STATS_SUCCESS: "SHOW_STATS_SUCCESS",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  CHANGE_PAGE: "CHANGE_PAGE",
};

export default actionTypes;
